const farmerMap = {
    "name" : "name",
    "father's name" : "fathersName", 
    "parent account" : "parentAccount",
    "feild id" : "feildId",
    "phone" : "phone",
    "long" : "long",
    "lat" : "lat",
    "surveyed Area" : "surveyedArea",
    "survey1_prescription map" : "map1link",
    "date of survey 2":"surveydate2",
    "survey2_prescription map" : "map2link",
    "date of survey 1":"surveydate1",
    "cellphone access" : "cellphoneAccess",
    "website" : "website",
    "source" : "source",
    "how many crops grown in last 1 year" : "cropsGrown",
    "tehsil" : "tehsil",
    "post" : "post",
    "description" : "description",
    "village" : "village",
    "block" : "block",
    "district" : "district",
    "billing street" : "billingStreet",
    "billing city" : "billingCity",
    "billing state" : "billingState",
    "billing zip/postal code" : "billingZipCode",
    "billing country" : "billingCountry",
    "shipping street" : "shippingStreet",
    "shipping city" : "shippingCity",
    "shipping state" : "shippingState",
    "shipping country" : "shippingCountry",
    "shipping zip/postal code" : "shippingZipCode",
    "major buyer of crop produced" : "majorBuyer",
    "total area under cultivation (in acres)" : "totalAreaUnderCultivation",
    "number of family members" : "familyMembers",
    "number of children" : "children",
    "cattle in house" : "cattles",
    "annual income of household from agri" : "annualIncome",
    "scanned aadhar card" : "aadhaarNumber",
    "name of bank" : "bankName",
    "ifsc code" : "ifsc",
    "bank account number" : "accountNumber"
}

const mapmap = {
    "Field ID - Final": "excel_id",
    "Field ID - Survey 2": "excel_id_2",
    "Area": "area",
    "goemetry": "geometry",
    "long": "long",
    "lat": "lat",
    "Farmer name": "farmer_name",
    "Contact": "contact",
    "Village": "village"
}

module.exports = {farmerMap, mapmap};